version: "3"

tasks:
  run:
    interactive: true
    cmds:
      - cmd: pnpm start

  open:
    interactive: true
    cmds:
      - cmd: node src/main.ts open

  check:
    cmds:
      - cmd: pnpm check
    silent: true
